# Generated by Django 3.2.22 on 2023-11-02 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_auto_20231031_1011"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="following",
        ),
    ]
