# Generated by Django 5.1 on 2025-03-10 10:29

import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Discover Featured Spots', max_length=200)),
                ('badge_text', models.CharField(default='New', max_length=50)),
                ('action_text', models.CharField(default="See what's new", max_length=100)),
                ('action_link', models.CharField(default='/locations/locations/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title (60 characters max)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO Description (160 characters max)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('main_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Main hero image (1920x1080 recommended)', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='home/')),
                ('heading', models.CharField(default='Show Your Spot', max_length=100)),
                ('subheading', models.CharField(default='Every Spot Tells A Story', max_length=200)),
                ('text', models.TextField(default="Discover hidden gems and share your favorite places with the world. Whether it's a tranquil nature retreat, a cozy café, or a breathtaking viewpoint - every spot tells a story. Share yours today.")),
                ('button1_text', models.CharField(default='Register Here', max_length=50)),
                ('button1_link', models.CharField(default='/account/register/', max_length=200)),
                ('button2_text', models.CharField(default='Log-In Here', max_length=50)),
                ('button2_link', models.CharField(default='/account/login/', max_length=200)),
                ('main_content', models.TextField(blank=True, null=True)),
                ('second_content', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title (60 characters max)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO Description (160 characters max)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('second_content', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
