# Generated by Django 3.2.22 on 2023-10-18 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0002_likelocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likelocation',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='likelocation',
            name='username',
        ),
        migrations.AddField(
            model_name='likelocation',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
