# Generated by Django 5.1 on 2025-03-09 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
