# Generated by Django 5.1 on 2025-03-12 21:13

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_comment_created_at_alter_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[400, 300], upload_to='locations/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1200, 900], upload_to='locations/'),
        ),
    ]
