# Generated by Django 3.2.22 on 2023-11-09 16:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
