# Generated by Django 5.1 on 2025-04-02 18:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_tag_location_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Location Description'),
        ),
    ]
