# Generated by Django 3.2.22 on 2023-11-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='locations.location'),
        ),
    ]
