# Generated by Django 3.2.22 on 2023-11-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_alter_like_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='location',
        ),
        migrations.AddField(
            model_name='like',
            name='location',
            field=models.ManyToManyField(related_name='likes', to='locations.Location'),
        ),
    ]
