# Generated by Django 3.2.22 on 2023-11-09 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20231109_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='location',
        ),
        migrations.AddField(
            model_name='like',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='locations.location'),
        ),
    ]
