# Generated by Django 5.1 on 2025-04-03 18:52

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_alter_location_location_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='External URL for photo (if not uploading directly)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1200, 900], upload_to='locations/'),
        ),
    ]
